import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle ,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image';
import profile from '../public/profile.png'






export default function Home() {
  return (
    <div >
      <Head>
        <title>Sneha portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-to-b from-amber-600 px-10">
       <section className=" min-h-screen">
       <nav className="py-10  flex justify-between">
       <h1 className="text-xl font-burtons">
          Portfolio
        </h1>
        <ul className="flex items-center">
          <li>
          <BsFillMoonStarsFill className="text-xl cursor-pointer"/>
          </li>
          <li>
            <a className="bg-gradient-to-t from-cyan-500 text-white px-4 py-2  rounded-md ml-6" href="https://mail-attachment.googleusercontent.com/attachment/u/1/?ui=2&ik=421db2a296&attid=0.1&permmsgid=msg-a:r8127334815354861462&th=17a22c67cc0ec4be&view=att&disp=inline&saddbat=ANGjdJ-aPj3GT0z2tzk7RzZDKj4z6M6-j2BZN_To-WXGUt4P-qpFpJ4Z7n0uK0ZyOiOHmStAaW_cgTamQGMoN4W2XL8gt9NDC-X1OA_iRNv_yw_XVX9FlBtsUGriQbmyKPpuq11yhM3h4gqpoBa3MwPZmFc-5ZB2_1mFzqyAJqQZ75OKI_js8A7D0p3ZeF4_fgHdFjFtGCgKDTSvVmnP9js_GV5__osEHQMUt46LJfsFQFao-vy6n-DsNUnDCsBy0fQIQ6rWkCK_sDgFxFrouHhFr7PsqM3CWD7XQrG0yOIY_wAvB74psk96pE-m2wh79VhlpVjbHLcNDPlosSDpmeohxcKv_D4DKcrZjCLr5rUNCeHHTpCPw3tJ0OA2zLtIZZeWXiQXiKdINUJjtkJwWZ-gYallAVgZMZifhboVFo2Vyd9pNxQGOhZuF51uBZgrbDOjXXWQQaVrGWOGhHaXEDTmbQnCNhlp-hVAewlYUj9wMHD_ti4FSbDYowVe0g-12ySw62pDX6qBWbCxNKV691lkCfvcRFFuU7I2WcbQcIsBrBEuVJN0ujA6033gVlDmxnO4pKzVguT4TVdxNfRTXe6xRLgMe4QRF1yGUcodS-Oadsdq13raZ5SyBadGU6figRXR77eSRJhKDgaf9NzRWeUt3zLzgfG86LJwb5JtGzyW6v6MZuKk0zZSknMo_U_SVjkgPEjHCim_jdjlNnM1UgYxO6GGV1xGBfY555atIUQiiDe9FlTAb5og1p4aliyq1BAY9njGE3xCdGTBgr4JB3wMBw7FKBNzrylQvqBhaT2REm3Z12UDM7OOw-CrbSxGH5Yu5Lc0BilxtHOXI90fb2JQQWfABPUOpC-Q79atDM9HIJwJhjUR0g7IxhxczaI243tVfOFOG0AI7gZG7Z4XeDikrek43zRZrrV3kYM9ajcOc1H_QazZLm4fr272Cf4xo26Z7BQwPe0T0mD9h7uh">Resume</a>
            </li>
        </ul>
       </nav>
       <div className="text-center p-10">
        <h2 className="text-5xl py-2 text-teal-600 font-semibold">Sneha Subramanian</h2>
        <h3 className="text-2xl py-2 font-serif">Front end web developer</h3>
        <p className="text-md py-5 leading-8 text-gray-800">
          Connect with me
        </p>
       </div>
       <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
        <AiFillTwitterCircle/>
        <a href="https://www.linkedin.com/in/sneha-subramanian-227140198/"><AiFillLinkedin  className="cursor-pointer"/></a>
        <AiFillYoutube/>
       </div>
      <div className="relative bg-gradient-to-b from-slate-500 rounded-full w-80 h-80 mx-auto">
        <Image 
        className="text-center absolute top-9
        left-11 rounded-full"
        src={profile}
        />
      </div>
       </section>
      </main>

      
    </div>
  )
}
